[workspace]
members = ["leetcode", "micro_util"]
resolver = "2"

[profile.release]
opt-level = 2

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 1
